### ISSUE TITLE
Parallel Download Issue with Saving Files

### ISSUE THREAD

**Issue by julianhtc** [scivision/nexrad-quick-plot#1]
Hello,
I am on the "Download NEXRAD Data" step and I'm having an issue. When I run the command, there are no errors; it even tells me x number of files are being saved in the folder I inputted. The issue is that there is nothing being saved in my chosen folder. Do you happen to know what is going on?

This is  what I'm running for reference:
python3 download_nexrad.py 2018-01-01T00 2018-01-03T00 /Users/gnss_user/Documents/nexradData/data

Thanks.

**Comment by scivision** [comment]
I'm not sure, I tried this command:
```sh
python3 download_nexrad.py 2018-01-01T00 2018-01-03T00 ~/data/asioqpoi
```
(just typed a random directory--the program creates that directory)

> downloading 576 files to ~/data/asioqpoi

and the files are there

**Comment by scivision** [comment]
I added self-tests for Mac and it seems to work there as well -- it looks like you're on a Mac.
When it's downloading, the current file name being downloaded is printed--do you see specific file names being printed?

**Comment by scivision** [comment]
Download timeout was added, this may address this issue of silently failing when internet has issue:
https://github.com/scivision/nexrad-quick-plot/releases/tag/v0.6.5
